### ISSUE TITLE
Exercise STYLISH CSS problem

### ISSUE THREAD

**Issue by diegofaria** [azat-co/expressworks#104]
The STYLISH CSS exercise is passing without the use of stylus middleware.
This solution is passing:

```
var express = require('express')
var port = process.argv[2]
var staticFilePath = process.argv[3]
var app = express()

app.use(express.static(staticFilePath))

app.listen(port)
```
It got me confused. :smile:

**Comment by azat-co** [comment]
@diegofaria not really, you just tried it many enough times so the official solution code generated `main.css` and your wrong solution used that file. here's the enhancement: https://github.com/azat-co/expressworks/commit/1f7767462956c331c4426a2cfee01b6058b90529

**Comment by diegofaria** [comment]
Oh ok, thank you @azat-co!
