### ISSUE TITLE
http://www.bit.ly/1jW1sBf

### ISSUE THREAD

**Issue by isomorphisms** [azat-co/expressworks#106]
The [help video](http://www.bit.ly/1jW1sBf) link displayed in `expressworks` #1 doesn't lead anywhere.

--------

Also if I paste the example code

```
    var express = require('express')
    var app = express()
    app.get('/', function(req, res) {
      res.end('Hello World!')
    })
    app.listen(3000)
```

into a file and `node example.js`, it doesn't run.

**Comment by azat-co** [comment]
@isomorphisms I just tested the link <http://www.bit.ly/1jW1sBf>. it works. I also tried in incognito mode and it works too. The YouTube link is https://www.youtube.com/watch?v=C2IqQOLCCoU&list=PLguYmmjtxbWGwQRxXqMTQCj6FNb55aFVo
