### ISSUE TITLE
Issue with port number on exercise 1

### ISSUE THREAD

**Issue by Euklidian-Space** [azat-co/expressworks#110]
Having an issue on the first exercise.  It seems the port that is given when I run

```
expressworks verify program.js
```
is making node give the following error.  

✗ Error connecting to http://localhost:24542/home: connect ECONNREFUSED 127.0.0.1:24542

However if I run the server from the terminal and give it an argument of 3000 (for the port) I can access it fine through my browser.  Maybe port 24542 is too high?  Not sure

**Comment by azat-co** [comment]
make sure you have nothing stuck as an old process. 
try 

```
killall node
```
