### ISSUE TITLE
Jade renamed to Pug

### ISSUE THREAD

**Issue by owenfromcanada** [azat-co/expressworks#111]
As of Dec. 2015, the Jade package was renamed to Pug.  Expressworks should refer to the newer package (see https://github.com/pugjs/pug/issues/2184).

**Comment by azat-co** [comment]
@owenfromcanada thanks for the heads up! feel free to make a PR if you want

**Comment by Riglerr** [comment]
I've submitted a PR for this: https://github.com/azat-co/expressworks/pull/112
