### ISSUE TITLE
Jade exercise cannot be completed

### ISSUE THREAD

**Issue by ghost** [azat-co/expressworks#30]
I'm using the exact same code as per the solution @ https://github.com/azat-co/expressworks/blob/master/problems/jade/solution.js

However, expressworks still deems this a fail:
![image](https://cloud.githubusercontent.com/assets/7820866/3713419/1fc50d7c-1569-11e4-828b-698bfc0479d5.png)

The 'jade' package is also installed locally, and globally.

**Comment by azat-co** [comment]
#58

**Comment by Beltayn** [comment]
I've been struggling with this for days now. I'm even running the official solution and I get the same error. 
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/workspace/ewExercises/jade.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
✗ Error connecting to http://localhost:59052/home: connect ECONNREFUSED
```
The official solution doesn't even 'require('jade') at the top. I've added that and installed jade via NPM, Nothing has worked.

**Comment by azat-co** [comment]
@Beltayn jade is part of package.json
https://github.com/azat-co/expressworks/blob/master/package.json#L29

you don't need to do require('jade') because express will do it for you... unless you want to call jade manually which I don't think you do in this exercise.

**Comment by Beltayn** [comment]
@azat-co Thanks for clarifying that. The course wasn't working without some kind of update though. I had to update NPM and install jade locally to get it to work. I can duplicate the error if you're interested.

**Comment by azat-co** [comment]
@Beltayn that can be helpful to others
