### ISSUE TITLE
Expressworks run program.js doesn't work on Windows

### ISSUE THREAD

**Issue by ericlathrop** [azat-co/expressworks#34]
Trying out the Hello World exercise in Windows, and I get an error:
```
C:\Users\Eric>node -v
v0.10.25

C:\Users\Eric>expressworks run expressworks.js
C:\Users\Eric\expressworks.js(1, 1) Microsoft JScript runtime error: Object expected
```
Not sure why it's running JScript. Node runs fine, and expressworks shows the menu fine.
My code looks like this:
```
var express = require("express");
var app = express();
app.get("/", function(req, res) {
	res.end("Hello World");
});
app.listen(process.argv[2]);
```

**Comment by alicejiang1** [comment]
Is this even still an issue? I copied the exact code above and, other than the path and response string being incorrect, it ran and verified just fine for me on a Windows machine...

**Comment by azat-co** [comment]
@alicejiang1 I think it's not an issue. I think the name of the file should be different from expresswork.js, e.g., `expressworks run program`
