### ISSUE TITLE
problem 7 & 8 expected solutions are wrong

### ISSUE THREAD

**Issue by morenoh149** [azat-co/expressworks#38]
straight up wrong
```
expressworks verify program.js
Verifying "WHAT'S IN QUERY"...

ACTUAL:   "{\"results\":\"recent\",\"type\":\"quote\",\"page\":\"7\"}"
EXPECTED: "Cannot GET /search/?results=recent&amp;type=quote&amp;page=7"

# FAIL

Your solution to WHAT'S IN QUERY didn't match the expected output.
Try again!
```
basically you can pass this problem by omitting the route. If you use the provided solution (or a correct solution as in my case) you do not pass this problem. I would fix it myself but I'm unfamiliar with the way the expected solution is generated in https://github.com/azat-co/expressworks/blob/master/problems/whats_in_query/setup.js
Also found problem 8 does something similar. I tried npm install express in these directories just in case that was the issue but it is not. Let me know if you have trouble reproducing the bug.

**Comment by morenoh149** [comment]
ping @QuincyLarson @FreeCodeCamp

**Comment by azat-co** [comment]
@morenoh149 try `killall node` #58
