### ISSUE TITLE
Cannot find module 'workshopper-exercise'

### ISSUE THREAD

**Issue by sergilokuay** [azat-co/expressworks#60]
Hi there!
When I run expressworks in the terminal and execute a problem I get this error:

module.js:338
    throw err;
          ^
Error: Cannot find module 'workshopper-exercise'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/expressworks/exercises/hello_world/exercise.js:3:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
--
I'm using OSX 10.6.8

banquisalm:express banquisalm$ node --version && express --version && expressworks --version
v0.12.0
4.11.2
expressworks@2.0.0

Cheers ;)

**Comment by baconisthecure** [comment]
I'm having the same issue on Windows 7.

**Comment by jess0407** [comment]
same here

**Comment by thomaslam** [comment]
same

**Comment by vazgen** [comment]
same

**Comment by ponkon** [comment]
Same issue

**Comment by sharkovich** [comment]
Just add this line to dependencies in package.json of expressworks module (error gives you location)

`"workshopper-exercise": "^2.3.0"`

Then run `npm install` in command line from inside expressworks folder
Works for me.

**Comment by jess0407** [comment]
Thanks sharkovich! It solves the issue, have sent the pull request with the fix.

**Comment by sergilokuay** [comment]
It worked for me too.
First install workshopper-exercise with npm
Locate and edit with 'vim' (w / permission ) /usr/local/lib/node_modules/expressworks/package.json
add the line above and save.

Thanks sharkovich!

**Comment by martinheidegger** [comment]
:+1:  closing issue

**Comment by sqlchow** [comment]
:+1: @sharkovich , thanks for the quick tip. this helps a lot.

**Comment by batjko** [comment]
Well, not for me.
I went into the expressworks sub folder, added the extra dependency and ran `npm install`, and I can see it having been installed, but I still get the same exception.

I'm on Win8.1, same is true on Win10 TP.

**Comment by ccysfn** [comment]
well done!
For me,under the location :
...
C:\Users\Administrator\AppData\Roaming\npm\node_modules\expressworks
...
add that line
then npm install
then "expressworks" worked

**Comment by lightonphiri** [comment]
Was having the same problem. Installing `workshopper-exercise` globally---as @batjko ---suggested is what worked for me as well.

**Comment by alexandarp** [comment]
Thank you @lightonphiri, it worked for me as well.

**Comment by NamanJn** [comment]
Yup, just install workshopper - exercise globally.

**Comment by azat-co** [comment]
merged, please update from NPM
thanks!
