### ISSUE TITLE
Tutorial is broken from the first lesson

### ISSUE THREAD

**Issue by gyaresu** [azat-co/expressworks#64]
Connection refused when running correct first lesson `expressworks verify app.js`

![screenshot 2015-04-11 13 09 02](https://cloud.githubusercontent.com/assets/29263/7103110/96d83b60-e04c-11e4-8622-58b75927bfbd.png)

**Comment by azat-co** [comment]
you are running servers already and the workshopper cannot start the servers it needs to start

`killall node` before verifying
