### ISSUE TITLE
Hello World Fails

### ISSUE THREAD

**Issue by cflanagan** [azat-co/expressworks#67]
The sample code for Hello World! is incorrect. The app.get statement directs uses to write:
app.get('/', function(){...})

when the correct answer is
app.get('/home', function(){...});

**Comment by azat-co** [comment]
@cflanagan everything is **correct**, '/' is a hint not the answer otherwise what is the point of giving a student the answer and only asking him/her to copy/paste? use hint only if you can't solve the question and use it as an example, not as the direct answer
