### ISSUE TITLE
expressworks #7 error

### ISSUE THREAD

**Issue by tvollmer89** [azat-co/expressworks#69]
having an issue passing exercise 7:
![screen shot 2015-05-15 at 8 42 42 am copy](https://cloud.githubusercontent.com/assets/4602882/7653877/ab159b2a-fade-11e4-8743-83294493523a.jpg)

**Comment by tvollmer89** [comment]
This is my code in program.js:

    var express = require('express')
    var app = express()

    app.get('/search', function(req, res){
      var query = req.query
      res.send(query)
    })

    app.listen(process.argv[2])

**Comment by prashcr** [comment]
You need to
1. Pass it as a JSON string (`stringify`)
2. Before that, remove the non-enumerable `__proto__` property (there's a hint right there)

**Comment by mdmoore** [comment]
```var express = require('express')
var app = express()

app.get('/search', function(req, res){
  var query = req.query
  delete query.__proto__;
  res.send(JSON.stringify(query));
})

app.listen(process.argv[2])```

**Comment by mdmoore** [comment]
```javascript
var express = require('express')
var app = express()

app.get('/search', function(req, res){
  var query = req.query
  delete query.__proto__;
  res.send(JSON.stringify(query));
})

app.listen(process.argv[2])
```

**Comment by tvollmer89** [comment]
That worked, thank you!
