### ISSUE TITLE
stylish css doesn't accept solution

### ISSUE THREAD

**Issue by ajvish** [azat-co/expressworks#78]
Big time noob here. Here is the code:

**var express = require('express')
var path = require('path')
var app = express()
app.use(require('stylus').middleware( process.argv[3] + "/*.styl" ))
app.get('/main.css', function(req, res) {
	res.end()
})
app.listen(process.argv[2])**

main.css is being generated, but the GET doesn't fetch it. Please help!

**Comment by marocchino** [comment]
you don't need to `get /main.css` just serve it as static file.

**Comment by ajvish** [comment]
Tried that. But it says **Cannot GET /main.css**. :/

**Comment by marocchino** [comment]
Did you serve main.css file after create it?

**Comment by ajvish** [comment]
@marocchino Yeah. I think that's what the *http.get()* is for right?

First, I convert the *.styl* file into *main.css* using **app.use(require('stylus').middleware( process.argv[3] + "/*.styl" ))**

After *main.css* is created, I serve it using:
**app.get('/', function(req, res) {
res.end()
})
app.listen(process.argv[2])**

Correct me if I am wrong, but is this the way to do this?

**Comment by nelsonlho** [comment]
type in:  sudo expressworks verify yourprogramname.js

**Comment by azat-co** [comment]
you're missing static middleware 

```
app.use(express.static(FOLDERNAME))
```

**Comment by PrinceOfShapeir** [comment]
I keep getting "stylus.middleware is not a fuction."

**Comment by azat-co** [comment]
@PrinceOfShapeir did you install stylus? issues are not for help. they are for bugs in the workshop.

**Comment by decksterr** [comment]
For anyone still trying to complete this, here's a solution that works: 
```javascript
var express = require('express');
var app = express();

app.use(express.static(process.argv[3]));
app.use(require('stylus').middleware(process.argv[3]));

app.listen(process.argv[2]);
```

Problem is that when running that piece of code, the "expected" answer is:
```
"Error: EACCES, open &#39;/usr/local/lib/node_modules/expressworks/exercises/stylish_css/public/main.css&#39;<br> &nbsp; &nbsp;at Error (native)"
```
And when running the command with `sudo` it seems the "expected" answer is the right one but somehow the "actual" response is `Cannot GET /main.css`

SO, this is definitely a bug.

PS: If you yet wish to mark the exercise as "completed" just validate it with this: 
```javascript
var express = require('express');
var app = express();

app.use(express.static(process.argv[3]));
// app.use(require('stylus').middleware(process.argv[3]));

app.get('/main.css', function (req, res) {
	res.end('p {\n  color: #f00;\n}\n')
})

app.listen(process.argv[2]);
```

**Comment by azat-co** [comment]
@decksterr i think you installed some modules with sudo, remove your node_modules and any related modules up the folder tree and try again.

**Comment by SharmaBiswadev** [comment]
var express=require('express');
var app=express();
 app.use(require('stylus').middleware(process.argv[3] || path.join(__dirname, 'public')))
app.use(express.static(process.argv[3] || path.join(__dirname, 'public')));
app.listen(process.argv[2]);

This worked well for me

**Comment by meta-karan-bhargava** [comment]
In case, anyone still reaches to end of this post, a gentle reminder to have a look at this line given in Hints:
**_Remember that middleware is executed in the order app.use is called!_**

We have to serve css file first, so use stylus middleware accordingly.

Thanks!
