### ISSUE TITLE
Official WHAT'S IN QUERY solution doesn't work

### ISSUE THREAD

**Issue by occult** [azat-co/expressworks#82]
The official solution is:
```
    var express = require('express')
    var app = express()
    
    app.get('/search', function(req, res){
      var query = req.query
      res.send(query)
    })
    
    app.listen(process.argv[2])
```
but it **doesn't** work. 

My solution was: 
```
var express = require('express');
var app = express();

app.get('/search', function (req, res) {
  var query = req.query;
  delete query.__proto__;
  res.send(JSON.stringify(query));
});

app.listen(process.argv[2]);
```
I don't know if it's a good solution, but it worked.

**Comment by Lemony-Andrew** [comment]
The official solution worked fine for me. Did you completely paste it to see for yourself?

**Comment by azat-co** [comment]
`delete query.__proto__;` is the only difference?

**Comment by youssefshb** [comment]
The official solution didn't work for me neither.

**Comment by dannytpeck** [comment]
Here's what I got with the Official Solution:

                 ACTUAL                                 EXPECTED                
    ───────────────────────────────────────────────────────────────────────────────

       "{"                                 !=    "{\"results\":\"recent\",\"type\":\"quote\",\"page\":\"10\"}"
       "  \"type\": \"quote\","            !=                                       
       "  \"page\": \"10\","               !=                                       
       "  \"__proto__\": {}"               !=                                       
       "}"                                 !=                                       

    ────────────────────────────────────────────────────────────────────────────────

I'm guessing it has something to do with my express version. I'm using 3.2.6 at the moment. Deleting \__proto\__ and using JSON.stringify worked like a charm!
