### ISSUE TITLE
JSON ME Unable to produce answer

### ISSUE THREAD

**Issue by su6a12** [azat-co/expressworks#85]
My answer below is almost identical to the official answer and produces the same output, which is not "correct" in that it spans multiple lines and the correct output is all one line.  I don't see anything wrong with my code.

var fs = require('fs');
var express = require('express');
var app = express();

app.get('/books', function(request, response) {
    fs.readFile(process.argv[3], function(error, data) {
        if (error) {
            console.log(error);
        }
        response.json(JSON.parse(data));
    });
});
app.listen(process.argv[2]);

**Comment by samscripts** [comment]
Hi try to use
response.send(JSON.stringify(JSON.parse(data)));

check for brackets...
Cheers, Sam

**Comment by su6a12** [comment]
@samscripts Thanks, it works with response.send(JSON.stringify(JSON.parse(data.toString())));
