### ISSUE TITLE
what's in query can't return correct format

### ISSUE THREAD

**Issue by canhongpoxiao** [azat-co/expressworks#88]
![image](https://cloud.githubusercontent.com/assets/10010222/10356909/81b1900c-6dae-11e5-90db-6373d6bea90c.png)
![image](https://cloud.githubusercontent.com/assets/10010222/10356917/98e98e32-6dae-11e5-8284-06a28b81e6b7.png)

**Comment by canhongpoxiao** [comment]
can anyone help me,thanks very much

**Comment by azat-co** [comment]
did you install express with -g?

https://github.com/azat-co/expressworks/issues/70

**Comment by canhongpoxiao** [comment]
thanks very much
