### ISSUE TITLE
STATIC - confused about instructions - where to learn more

### ISSUE THREAD

**Issue by bessieatrazoyo** [azat-co/expressworks#98]
I am finding the ExpressWorks instructions incomprehensible.  Perhaps I am missing some prerequisites.  I’ve written out my questions below to show the level of ignorance I am coming to this learning session with.  If you have suggestions about where to go to learn what I need before I start, please let me know.

For example, Exercise 2 of 8 (static) says:

Please don't use ANY routes like app.get. ONLY static.

I wonder:
1. What is a route?
2. How can I learn about app?
3. Static?  Static as opposed to dynamic.  What does that mean?

Your solution must listen on the port number supplied by process.argv[2].

I wonder:
4. What listens?
5. Is this like the Hello World one where I used this:
var app = express();
...
app.listen(process.argv[2]);

This is how you can call static middleware:

I wonder:
6. What is static middleware?
7. Where can I learn about it?

For this exercise expressworks will pass you the path:

    app.use(express.static(process.argv[3] || path.join(__dirname, 'public')))

I wonder:
8. Is app var app = express();?
9. If so, what is express?
10.  Where did the path variable come from?

This what I think is supposed to happen:  process.argv[3] points to an HTML file.  I am supposed get this HTML file and send it back in a response.  I’m supposed to wait for a request from process.argv[2], but I don’t know if I’m supposed to parse that request in any way.

**Comment by TylerMoeller** [comment]
The best place to start is with the command: `expressworks help`

This will give you a link to the API documentation and another to a book written by azat-co. 

**API docs**: http://expressjs.com/api.html
**Express.js Guide**: http://expressjsguide.com

The API docs should answer your questions:
- routes: http://expressjs.com/guide/routing.html
- app: http://expressjs.com/4x/api.html#app
- static: http://expressjs.com/starter/static-files.html
- etc.

Hope this helps.

**Comment by bessieatrazoyo** [comment]
Thank you very much the links to expressjs.com is what I was looking for.  It will be a while before I can get back to it, but I'll post how it went when I do.  Keep it open for now.

**Comment by bessieatrazoyo** [comment]
Evan Hahn's blog post:  http://evanhahn.com/understanding-express/ helped me out.

**Comment by azat-co** [comment]
@TylerMoeller thanks ;)
